name: Ma première CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    # On utilise l'Ubuntu latest pour la build
    runs-on: ubuntu-latest

    steps:
      # On récupère le code via le git
      - uses: actions/checkout@v3
      # On utilise/install Node.js 20.x
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      # On installe les dépendances
      - run: npm ci
      # On lance le linter
      - run: npm run lint
      # On lance les tests
      - run: npm test
  deploy:
    run-on: ubuntu
    staps:
      -uses: 
       with:
        api-key: rnd_uQwJBLbZUyZaG5nCohcvFOUMWiQo
        service id: srv-d5pieishg0os739jcbjg

#TP Part 3 : Automatiser la détection (SCA)
-CA - Audit des dépendances
run: npm audit --audit-level=high
#TP Part 4 : Automatiser la détection (SAST)
-Scan du code source (Semgrep)
 uses: semgrep/semgrep-action@v1
 with:
 config: p/javascript


# --- NOTIFICATION EN CAS D'ÉCHEC ---
- name: Notification d'échec (Discord)
  if: failure()
  run: |
  # --- TP Part 5 : La Boucle de Rétroaction (Feedback) ---
  echo "### ❌ Échec de la Pipeline de Sécurité" >> $GITHUB_STEP_SUMMARY

  # Envoi d'un Webhook Discord
  # Les étudiants doivent créer un Webhook dans Discord et l'ajouter en secret : DISCORD_WEBHOOK
  curl -H "Content-Type: application/json" \
     -X POST \
     -d "{\"content\": \"Ça marche pas !\"}" \
     ${{ secrets.DISCORD_WEBHOOK }}

 